# Generated by Django 4.1.1 on 2022-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('idservice', models.IntegerField(db_column='idService', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Сервисы',
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=64, unique=True)),
                ('user_password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('iduserservice', models.AutoField(db_column='idUserService', primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('order_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Сервисы пользователей',
                'db_table': 'user_service',
                'managed': False,
            },
        ),
    ]
